# Encapsulate the steps to merge code coverage reports
# You can call this action wit the following:
# 
# steps:
#   ...
#   # make sure to checkout the code before running the local action
#   - uses: actions/checkout@v2
#   - uses: ./.github/workflows/actions/merge-cov

name: 'Merge code coverage reports'
description: 'Merge the coverage reports from all of the different test runs.'

outputs:
  # return the filename of the final coverage report (if needed by downstream)
  cov-report-filename:
    description: "Filename of the code coverage report"
    value: ${{ steps.show-final-report.outputs.cov-report-final }}

runs:
  using: "composite"
  steps:
  - name: Install dev-dependencies
    shell: bash
    run: |
      pip install --upgrade pip setuptools wheel
      python -m pip install coverage

  - name: Show downloaded coverage reports
    shell: bash
    run: ls .coverage*
      
  # Merge code coverage reports so the coverage numbers are accurate across
  # different parallelized runs
  - name: Merge coverage reports
    shell: bash
    # NOTE: Merging code reports generated from self-hosted (aml) runners can be problematic
    #       as reports may reference the source code at an unresolvable absolute path.
    #       For example, you may encounter errors like:
    #            "CoverageWarning: Couldn't parse 
    #            '/home/azureuser/runner/work/recommenders/recommenders/recommenders/evaluation/__init__.py':
    #            No source for code"
    # Work-around: Creating a symlink at the root that points to the default local runner folder: '/home/runner/work/recommenders'
    run: |
      sudo mkdir -p /home/azureuser
      sudo ln -s /home/runner /home/azureuser/runner
      python -m coverage combine .coverage*
      python -m coverage report -i
      python -m coverage xml -i
      
  - name: Show merged report
    id: show-final-report
    shell: bash
    run: |
      echo "Final code coverage report: '$(ls *.xml)'"
      echo "::set-output name=cov-report-final::$(echo $(ls *.xml))"
