#data
#data format:ffm
data:
     train_file  : ../data/ml-100k/ml-100k/ua.base.reg.final # use .reg.final for regression data
     eval_file  :  ../data/ml-100k/ml-100k/ua.test.reg.final
     test_file  : ../data/ml-100k/ml-100k/ua.test.reg.final
     infer_file  :  ../data/ml-100k/ml-100k/ua.test.reg.final
     FIELD_COUNT :  5
     FEATURE_COUNT : 213
     data_format : ffm

#model
#model_type:deepFM or deepWide or dnn or ipnn or opnn or fm or lr
model:
    #method : classification
    method : regression
    model_type : exDeepFM
    dim : 10
    layer_sizes : [400, 400]
    activation : [relu, relu]
    dropout : [0.0, 0.0]
    cross_layer_sizes : [100, 100, 50]
    infer_model_name : epoch_2
#    load_model_name : ./checkpoint/epoch_1


#train
#init_method: normal,tnormal,uniform,he_normal,he_uniform,xavier_normal,xavier_uniform
train:
    init_method: tnormal
    init_value : 0.01
    embed_l2 : 0.0000
    embed_l1 : 0.0000
    layer_l2 : 0.0000
    layer_l1 : 0.0000
    cross_l2 : 0.0000
    cross_l1 : 0.000
    learning_rate : 0.001
    #loss : log_loss
    loss : square_loss
    optimizer : adam
    epochs : 10
    batch_size : 128

#show info
#metric :'auc','logloss', 'group_auc'
info:
    show_step : 20
    save_epoch : 2
    metrics : ['rmse','mae','rsquare','exp_var','map_at_k','ndcg_at_k','precision_at_k','recall_at_k']

test:
    topN_flag : False

