name: xDeepFM-criteo
channels:
  - defaults
dependencies:
  - _tflow_1100_select=0.0.1=gpu
  - absl-py=0.4.1=py36_0
  - appdirs=1.4.3=py36h28b3542_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.7.1=py36_0
  - atomicwrites=1.2.1=py36_0
  - attrs=18.2.0=py36h28b3542_0
  - automat=0.7.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=2.1.4=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py36_1
  - cffi=1.11.5=py36he75722e_1
  - constantly=15.1.0=py36h28b3542_0
  - cryptography=2.3.1=py36hc365091_0
  - cudatoolkit=9.2=0
  - cudnn=7.2.1=cuda9.2_0
  - cupti=9.2.148=0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.0=py36_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - grpcio=1.12.1=py36hdbcaa40_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - html5lib=1.0.1=py36_0
  - hyperlink=18.0.0=py36_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py36_0
  - incremental=17.5.0=py36_0
  - intel-openmp=2019.0=118
  - ipykernel=4.9.0=py36_0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.1=py36_0
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36_0
  - jupyter=1.0.0=py36_6
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py36_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.6.0=hdbcaa40_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markdown=2.6.11=py36_0
  - markupsafe=1.0=py36h14c3975_1
  - mistune=0.8.3=py36h14c3975_1
  - mkl=2019.0=118
  - mkl_fft=1.0.4=py36h4414c95_1
  - mkl_random=1.0.1=py36h4414c95_1
  - more-itertools=4.3.0=py36_0
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=hf484d3e_0
  - notebook=5.6.0=py36_0
  - numpy=1.15.1=py36h1d66e8a_0
  - numpy-base=1.15.1=py36h81de0dd_0
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.23.4=py36h04863e7_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=10.0.1=py36_0
  - pluggy=0.7.1=py36h28b3542_0
  - prometheus_client=0.3.1=py36h28b3542_0
  - prompt_toolkit=1.0.15=py36_0
  - protobuf=3.6.0=py36hf484d3e_0
  - ptyprocess=0.6.0=py36_0
  - py=1.6.0=py36_0
  - pyasn1=0.4.4=py36h28b3542_0
  - pyasn1-modules=0.2.2=py36_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyqt=5.9.2=py36h22d08a2_1
  - pytest=3.8.0=py36_0
  - python=3.6.6=hc3d631a_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pyzmq=17.1.2=py36h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - qtconsole=4.4.1=py36_0
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py36_0
  - service_identity=17.0.0=py36h28b3542_0
  - setuptools=40.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.12=py36he6710b0_0
  - six=1.11.0=py36_1
  - sqlite=3.24.0=h84994c4_0
  - tensorboard=1.10.0=py36hf484d3e_0
  - tensorflow=1.10.0=gpu_py36hcebf108_0
  - tensorflow-base=1.10.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.10.0=hf154084_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1=py36h14c3975_0
  - traitlets=4.3.2=py36_0
  - twisted=18.7.0=py36h14c3975_1
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.4.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=ha838bed_2
  - zope=1.0=py36_1
  - zope.interface=4.5.0=py36h14c3975_0
prefix: /home/markus/miniconda3/envs/xDeepFM-criteo

