name: xDeepFM-criteo
channels:
  - defaults
dependencies:
  - _tflow_1100_select=0.0.1
  - _tflow_190_select=0.0.1
  - absl-py=0.4.1
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - astor=0.7.1
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - automat=0.7.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=2.1.4
  - ca-certificates=2018.03.07
  - certifi=2018.8.24
  - cffi=1.11.5
  - constantly=15.1.0
  - cryptography=2.3.1
  - cudatoolkit=9.0
  - cudnn=7.1.2
  - cupti=9.0.176
  - cycler=0.10.0
  - dbus=1.13.2
  - decorator=4.3.0
  - entrypoints=0.2.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.0
  - glib=2.56.2
  - gmp=6.1.2
  - grpcio=1.12.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - incremental=17.5.0
  - intel-openmp=2019.0
  - ipykernel=4.9.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.1
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.34
  - libprotobuf=3.6.0
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - markdown=2.6.11
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mistune=0.8.3
  - mkl=2019.0
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - more-itertools=4.3.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.6.0
  - numpy=1.15.1
  - numpy-base=1.15.1
  - openssl=1.0.2p
  - packaging=17.1
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - pluggy=0.7.1
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - protobuf=3.6.0
  - ptyprocess=0.6.0
  - py=1.6.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pytest=3.8.0
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.9.6
  - qtconsole=4.4.1
  - readline=7.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.24.0
  - tensorboard=1.9.0
  - tensorflow=1.9.0
  - tensorflow-base=1.9.0
  - tensorflow-gpu=1.9.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.8
  - tornado=5.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.31.1
  - widgetsnbextension=3.4.1
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.5.0
  - pip:
    - adal==1.1.0
    - ansiwrap==0.8.3
    - azure-datalake-store==0.0.31
    - azure-nspkg==2.0.0
    - black==18.6b4
    - blackcellmagic==0.0.1
    - boto3==1.9.13
    - botocore==1.12.13
    - chardet==3.0.4
    - click==6.7
    - docutils==0.14
    - future==0.16.0
    - jmespath==0.9.3
    - papermill==0.15.0
    - pyjwt==1.6.4
    - requests==2.19.1
    - s3transfer==0.1.13
    - textwrap3==0.9.1
    - toml==0.9.6
    - tqdm==4.26.0
    - urllib3==1.23
prefix: /home/markus/miniconda3/envs/xDeepFM-criteo

